// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEiFLCZV5w1EcAWJWojnbH45S9w9Ld1zw',
    appId: '1:631089975040:web:692b10166da1680a4e2de5',
    messagingSenderId: '631089975040',
    projectId: 'readmev2',
    authDomain: 'readmev2.firebaseapp.com',
    storageBucket: 'readmev2.firebasestorage.app',
    measurementId: 'G-VX3ZDJGY31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSq0gaCURUoJXngRHtvMhpn4D9MGtTZ3A',
    appId: '1:631089975040:android:a561ac51a84272e64e2de5',
    messagingSenderId: '631089975040',
    projectId: 'readmev2',
    storageBucket: 'readmev2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfWfietFelt4atf50rRkhCM6A_2lzMk9s',
    appId: '1:631089975040:ios:538ba87faed6db874e2de5',
    messagingSenderId: '631089975040',
    projectId: 'readmev2',
    storageBucket: 'readmev2.firebasestorage.app',
    iosBundleId: 'com.example.readmeV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfWfietFelt4atf50rRkhCM6A_2lzMk9s',
    appId: '1:631089975040:ios:538ba87faed6db874e2de5',
    messagingSenderId: '631089975040',
    projectId: 'readmev2',
    storageBucket: 'readmev2.firebasestorage.app',
    iosBundleId: 'com.example.readmeV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEiFLCZV5w1EcAWJWojnbH45S9w9Ld1zw',
    appId: '1:631089975040:web:4b46d261789967884e2de5',
    messagingSenderId: '631089975040',
    projectId: 'readmev2',
    authDomain: 'readmev2.firebaseapp.com',
    storageBucket: 'readmev2.firebasestorage.app',
    measurementId: 'G-F8CS6THB4H',
  );

}