// analyze_book_structure.js
// Analyzes the required book structure for admin portal compatibility

const admin = require('firebase-admin');

try {
  const serviceAccount = require('./serviceAccountKey.json');
  admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
    projectId: 'readme-40267',
  });
  console.log('✅ Firebase connected');
} catch (error) {
  console.log('Firebase already initialized');
}

const db = admin.firestore();

async function analyzeBookStructure() {
  try {
    console.log('📋 BOOK STRUCTURE ANALYSIS FOR ADMIN PORTAL\n');
    console.log('=' .repeat(60));
    
    // Get a well-structured book as reference
    const booksSnapshot = await db.collection('books')
      .where('needsTagging', '==', false)
      .limit(3)
      .get();
    
    if (booksSnapshot.empty) {
      console.log('❌ No properly structured books found');
      return;
    }
    
    console.log('📚 ANALYZING WELL-STRUCTURED BOOKS:\n');
    
    const allFields = new Set();
    const fieldTypes = {};
    const examples = {};
    
    booksSnapshot.forEach((doc, index) => {
      const data = doc.data();
      console.log(`${index + 1}. "${data.title}" by ${data.author}`);
      console.log(`   ID: ${doc.id}`);
      console.log(`   Fields: ${Object.keys(data).length}`);
      
      // Collect all fields
      Object.keys(data).forEach(field => {
        allFields.add(field);
        fieldTypes[field] = typeof data[field];
        if (!examples[field]) {
          examples[field] = data[field];
        }
      });
      console.log('');
    });
    
    console.log('🏗️  REQUIRED BOOK STRUCTURE FOR ADMIN PORTAL:');
    console.log('=' .repeat(60));
    
    // Sort fields by importance
    const requiredFields = [
      'title', 'author', 'description', 'ageRating', 'pdfUrl', 
      'displayCover', 'createdAt', 'needsTagging'
    ];
    
    const optionalFields = Array.from(allFields).filter(f => !requiredFields.includes(f));
    
    console.log('\n📋 REQUIRED FIELDS (must be included):');
    requiredFields.forEach(field => {
      if (allFields.has(field)) {
        const type = Array.isArray(examples[field]) ? 'array' : fieldTypes[field];
        console.log(`   ✅ ${field}: ${type}`);
        if (field === 'needsTagging') {
          console.log(`      └─ CRITICAL: Must be set to true for new uploads`);
        }
        if (field === 'pdfUrl') {
          console.log(`      └─ Must point to valid Firebase Storage file`);
        }
        if (field === 'createdAt') {
          console.log(`      └─ Firebase Timestamp object`);
        }
      } else {
        console.log(`   ❌ ${field}: MISSING`);
      }
    });
    
    console.log('\n📝 OPTIONAL FIELDS (auto-generated by AI):');
    optionalFields.forEach(field => {
      if (allFields.has(field)) {
        const type = Array.isArray(examples[field]) ? 'array' : fieldTypes[field];
        console.log(`   • ${field}: ${type}`);
        if (field === 'traits' || field === 'tags') {
          console.log(`     └─ Generated by AI tagging system`);
        }
      }
    });
    
    console.log('\n💾 ADMIN PORTAL JSON TEMPLATE:');
    console.log('=' .repeat(60));
    
    const template = {
      title: "string - Book title",
      author: "string - Author name", 
      description: "string - Book description",
      ageRating: "string - Age rating (e.g., '6+', '8+', '12+')",
      pdfUrl: "string - Firebase Storage URL to PDF file",
      displayCover: "string - Cover image/emoji",
      createdAt: "Firestore.Timestamp - Creation timestamp",
      needsTagging: "boolean - MUST be true for new books",
      // Optional fields (don't include in admin upload):
      // traits: [], // Generated by AI
      // tags: [],  // Generated by AI
    };
    
    console.log(JSON.stringify(template, null, 2));
    
    console.log('\n🔧 ADMIN PORTAL IMPLEMENTATION CHECKLIST:');
    console.log('=' .repeat(60));
    console.log('□ Ensure PDF file uploads to Firebase Storage correctly');
    console.log('□ Store the correct Firebase Storage URL in pdfUrl field');
    console.log('□ Set needsTagging: true for all new uploads');
    console.log('□ Use Firestore.Timestamp for createdAt field');
    console.log('□ Validate all required fields before saving');
    console.log('□ Do NOT include traits or tags fields (AI will add them)');
    
    console.log('\n🚨 CRITICAL POINTS:');
    console.log('=' .repeat(60));
    console.log('1. needsTagging: true is ESSENTIAL for AI processing');
    console.log('2. pdfUrl must be valid Firebase Storage URL');
    console.log('3. Do NOT pre-populate traits/tags arrays');
    console.log('4. Use consistent field names and types');
    
    console.log('\n📝 EXAMPLE ADMIN UPLOAD CODE SNIPPET:');
    console.log('=' .repeat(60));
    console.log(`
// When creating a new book in admin portal:
const newBook = {
  title: formData.title,
  author: formData.author,
  description: formData.description,
  ageRating: formData.ageRating,
  pdfUrl: uploadedPdfUrl, // From Firebase Storage upload
  displayCover: formData.coverEmoji,
  createdAt: admin.firestore.Timestamp.now(),
  needsTagging: true // CRITICAL: Flags for AI processing
  // Do NOT include: traits, tags (AI will add these)
};

await db.collection('books').add(newBook);
    `);
    
  } catch (error) {
    console.error('❌ Error:', error);
  }
}

analyzeBookStructure();